steps:
# build image
- id: build
  name: 'gcr.io/kaniko-project/executor'
  args: [
    '--destination=gcr.io/$PROJECT_ID/greetings:$SHORT_SHA',
    '--cache=true',
    '--cache-ttl=12h',
    '--verbosity=error' ]

# test image
- id: test
  name: 'gcr.io/$PROJECT_ID/greetings:$SHORT_SHA'
  args: ['npx', '-v']
  env:
  - 'HOME=/app'
  wait_for: ['build']

# push image to registry
# - id: push
#   name: 'gcr.io/cloud-builders/docker'
#   args: [ 'push', 'gcr.io/$PROJECT_ID/greetings:$SHORT_SHA' ]
#   wait_for: ['test']

# render template for DEV environment
- id: template
  name: 'gcr.io/$PROJECT_ID/helm'
  args: ['template', 'greetings', 
    '--output-dir', '.', 
    '--values', 'greetings/dev.yaml', 
    '--set', 'projectId=$PROJECT_ID', 
    '--set', 'appVersion=$SHORT_SHA']
  env:
  - CLOUDSDK_COMPUTE_REGION=us-west1
  - CLOUDSDK_CONTAINER_CLUSTER=development-us-west1
  wait_for: ['test']

# deploy to DEV environment
- id: deploy-dev
  name: 'gcr.io/cloud-builders/gke-deploy'
  args: ['apply', '--filename=greetings/templates', '--location=us-west1', '--cluster=development-us-west1']
  wait_for: ['template']
