steps:
- id: build
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/greetings:$SHORT_SHA', '.' ]
images:
- 'gcr.io/$PROJECT_ID/greetings:latest'
- 'gcr.io/$PROJECT_ID/greetings:$SHORT_SHA'