version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.4.0
workflows:
  build-and-push-image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: greetings
          tag: "${CIRCLE_SHA1},latest"