version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.4.0

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      # - two:
      #     requires:
      #       - one

jobs:
  one:
    docker:
      - image: raizv/cli
    steps:
      - checkout
      - run: aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name cluster-1
      - run: kubectl get ns
      - run: helm template chart -f eks/chart/production.yaml | kubectl apply -f - -n trguest

# workflows:
#   build-and-push-image:
#     jobs:
#       - aws-ecr/build-and-push-image:
#           account-url: AWS_ACCOUNT_URL
#           region: AWS_DEFAULT_REGION
#           repo: greetings
#           tag: "${CIRCLE_SHA1},latest"
