version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.4.0

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: greetings
          tag: "${CIRCLE_SHA1},latest"
      - deploy-stage:
          requires:
            - aws-ecr/build-and-push-image
      # - deploy-prod:
      #     requires:
      #       - deploy-stage
jobs:
  deploy-stage:
    docker:
      - image: raizv/cli
        environment:
            ENVIRONMENT: stage
    steps:
      - checkout
      - run: |
          aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name ${ENVIRONMENT}
          helm template eks/chart -f eks/chart/${ENVIRONMENT}.yaml --set image.version=${CIRCLE_SHA1}|kubectl apply -f - -n trguest
          kubectl rollout status deployment/greetings -w -n trguest

  deploy-prod:
    docker:
      - image: raizv/cli
        environment:
            ENVIRONMENT: prod
    steps:
      - checkout
      - run: |
          aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name ${ENVIRONMENT}
          helm template eks/chart -f eks/chart/${ENVIRONMENT}.yaml --set image.version=${CIRCLE_SHA1}|kubectl apply -f - -n trguest
          kubectl rollout status deployment/greetings -w -n trguest
