apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    # external-dns.alpha.kubernetes.io/hostname: {{ .Values.name }}.{{ .Values.environment }}.{{ .Values.domain }}
spec:
  rules:
    # - host: {{ .Values.name }}.{{ .Values.environment }}.{{ .Values.domain }}
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ .Values.name }}
              servicePort: {{ .Values.service.port }}
