apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    # - host: greetings.cluster1.aws.raizv.net
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ .Values.name }}
              servicePort: {{ .Values.service.port }}
