apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: {{ .Values.appName }}
          image: "gcr.io/{{ .Values.projectId }}/greetings:{{ .Values.appVersion }}"
          env:
            - name: APP_ENV
              value: APP_ENV
          ports:
            - containerPort: {{ .Values.port }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /version
              port: {{ .Values.port }}
            initialDelaySeconds: 1
            timeoutSeconds: 1
          # gracefull shutdown
          lifecycle:                   
            preStop:                   
              exec:                    
                command:               
                - sh
                - -c
                - "sleep 5"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
