apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  name: ing
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.appName }}
          servicePort: {{ .Values.port }}
        path: /*
