apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.gkeServiceAccount }}@{{ .Values.projectId }}.iam.gserviceaccount.com"
  labels:
    app: {{ .Values.appName }}
  name: default
  namespace: {{ .Values.namespace }}